#!/usr/bin/env sh

# cargo build --release
cargo build
rm ./liq.hex
objcopy -O ihex ./target/thumbv7m-none-eabi/debug/liquidled-testrs liq.hex
# objcopy -O ihex ./target/thumbv7m-none-eabi/debug/liquidled-testrs liq.hex
stm32flash -i -dtr,rts:dtr,rts /dev/ttyUSB0
stm32flash /dev/ttyUSB0 -w ./liq.hex -v -g 0x0
